ingresses:
  - hosts:
    - name: hubble.blindfolded.surgery
    secret: tls-hubble-ingress
    issuer: letsencrypt-issuer
    name: hubble
    namespace: kube-system
    service:
      name: hubble-ui
      port: 80
