{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issue-temporary-certificate: "false"
      cert-manager.io/cluster-issuer: {{ default "letsencrypt-issuer" .issuer }}
spec:
  tls:
    - secretName: {{ .secret }}
      hosts:
      {{- range $host := .hosts }}
      - {{ $host.name }}
      {{- end }}
  rules:
  {{ $ingress := . }}
  {{- range $host := .hosts }}
  {{ with $host }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        pathType: {{ default "Prefix" .prefix }}
        backend:
          service:
            {{- with $ingress.service }}
            name: {{ default "http" .name }}
            port:
              number: {{ .port }}
            {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}